import { Inter } from "next/font/google"
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body >
        <Navbar></Navbar>
        <main className="py-8">
        {children}
        </main>
     
      </body>
    </html>
  );
}
